<h2>--- Day 9: Smoke Basin ---</h2><p>These caves seem to be <a href="https://en.wikipedia.org/wiki/Lava_tube" target="_blank">lava tubes</a>. Parts are even still volcanically active; small hydrothermal vents release smoke into the caves that slowly <span title="This was originally going to be a puzzle about watersheds, but we're already under water.">settles like rain</span>.</p>
<p>If you can model how the smoke flows through the caves, you might be able to avoid it and be that much safer. The submarine generates a heightmap of the floor of the nearby caves for you (your puzzle input).</p>
<p>Smoke flows to the lowest point of the area it's in. For example, consider the following heightmap:</p>
<pre><code>2<em>1</em>9994321<em>0</em>
3987894921
98<em>5</em>6789892
8767896789
989996<em>5</em>678
</code></pre>
<p>Each number corresponds to the height of a particular location, where <code>9</code> is the highest and <code>0</code> is the lowest a location can be.</p>
<p>Your first goal is to find the <em>low points</em> - the locations that are lower than any of its adjacent locations. Most locations have four adjacent locations (up, down, left, and right); locations on the edge or corner of the map have three or two adjacent locations, respectively. (Diagonal locations do not count as adjacent.)</p>
<p>In the above example, there are <em>four</em> low points, all highlighted: two are in the first row (a <code>1</code> and a <code>0</code>), one is in the third row (a <code>5</code>), and one is in the bottom row (also a <code>5</code>). All other locations on the heightmap have some lower adjacent location, and so are not low points.</p>
<p>The <em>risk level</em> of a low point is <em>1 plus its height</em>. In the above example, the risk levels of the low points are <code>2</code>, <code>1</code>, <code>6</code>, and <code>6</code>. The sum of the risk levels of all low points in the heightmap is therefore <code><em>15</em></code>.</p>
<p>Find all of the low points on your heightmap. <em>What is the sum of the risk levels of all low points on your heightmap?</em></p>

In [21]:
import numpy

with open("input.txt", "r") as file:
    heightmap = numpy.array([list(map(int, list(l.strip()))) for l in file.readlines()], dtype=numpy.float_)
heightmap = numpy.pad(heightmap, pad_width=1, constant_values=-numpy.inf) # type: ignore

risk_level = numpy.float_(0)

for i, j in numpy.ndindex(heightmap.shape):
    current = heightmap[i, j]
    if current == -numpy.inf:
        continue
    neighbors = numpy.array([heightmap[i-1, j], heightmap[i, j+1], heightmap[i+1, j], heightmap[i, j-1]])
    neighbors = neighbors[neighbors != -numpy.inf]
    if current < min(neighbors):
        risk_level += current + 1
print(int(risk_level))

550


In [42]:
with open("test.txt", "r") as file:
    heightmap = numpy.array([list(map(int, list(l.strip()))) for l in file.readlines()], dtype=numpy.float_)

heightmap = numpy.pad(heightmap, pad_width=1, constant_values=-numpy.inf) # type: ignore
low_points: list[tuple[int, int]] = []

for i, j in numpy.ndindex(heightmap.shape):
    current = heightmap[i, j]
    if current == -numpy.inf:
        continue
    neighbors = numpy.array([heightmap[i-1, j], heightmap[i, j+1], heightmap[i+1, j], heightmap[i, j-1]])
    neighbors = neighbors[neighbors != -numpy.inf]
    if current < min(neighbors):
        low_points.append((i, j))


def get_basin(point: tuple[int, int, int]) -> list[tuple[int, int, int]]:
    r, c, value = point
    neighbors = numpy.array([
        [r-1, c, heightmap[r-1, c]],
        [r, c+1, heightmap[r, c+1]],
        [r+1, c, heightmap[r+1, c]],
        [r, c-1, heightmap[r, c-1]],
    ])
    neighbors = neighbors[neighbors[:, 2] != -numpy.inf]
    higher_neighbors = neighbors[neighbors[:, 2] == value+1]
    if len(higher_neighbors) == 0:
        return []
    numpy.array([]).flatten().tolist()
    (get_basin(n) for n in higher_neighbors)



for i, j in low_points:
    low_point = heightmap[i, j]
    basin_size = 1
    frontier = [[i, j, low_point]]
    print(frontier)
    
    while len(frontier) > 0:
        for r, c, current in frontier:
            r, c = int(r), int(c)
            neighbors = numpy.array([
                [r-1, c, heightmap[r-1, c]],
                [r, c+1, heightmap[r, c+1]],
                [r+1, c, heightmap[r+1, c]],
                [r, c-1, heightmap[r, c-1]],
            ])
            neighbors = neighbors[neighbors[:, 2] != -numpy.inf]
            higher_neighbors = neighbors[neighbors[:, 2] == current+1]
            basin_size += higher_neighbors.shape[0]
            frontier = higher_neighbors
    print(basin_size)

[[1. 2. 1.]]
3
[[ 1. 10.  0.]]
10
[[3. 3. 5.]]
18
[[5. 7. 5.]]
7
